package default

from std import collection.*
// import org.antlr.v4.runtime.Parser;
// import org.antlr.v4.runtime.RecognitionException;
// import org.antlr.v4.runtime.Token;
// import org.antlr.v4.runtime.TokenStream;

open public class ErrorInfo <: DecisionEventInfo {

    public init (decision: Int32, configs: ATNConfigSet, input: Option<TokenStream>, startIndex: Int32, stopIndex: Int32, fullCtx: Bool){

    }

    public init() {}
}


