package default


open public class IntegerStack <: IntegerList {

    public init (){

    }

    public init (capacity: Int32){

    }

    public init (list: IntegerStack){

    }

    public open func push (value: Int32): Unit {
  //    add(value);

        
    }

    public open func pop (): Int32 {
  //    return removeAt(size() - 1);

        return 0
    }

    public open func peek (): Int32 {
  //    return get(size() - 1);

        return 0
    }

}


