package misc

// import org.antlr.v4.runtime.BailErrorStrategy;
// import org.antlr.v4.runtime.RecognitionException;
// import java.util.concurrent.CancellationException;

open public class ParseCancellationException <: CancellationException {

    public init (){

    }

    public init (message: String){

    }

    public init (cause: Throwable){

    }

    public init (message: String, cause: Throwable){

    }

}


